# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Sat Jan  5 14:50:04 PST 2013
#
#/ usage: gogrid:add-server  --apikey <The API key used to authenticate to GoGrid>  --secret <>  --server-name <>  --server-image <>  --server-ram <>  --server-description <> [ --public-ip <>] [ --private-ip <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --apikey) rerun_option_check $# $1; APIKEY=$2 ; shift ;;
            --secret) rerun_option_check $# $1; SECRET=$2 ; shift ;;
            --server-name) rerun_option_check $# $1; SERVER_NAME=$2 ; shift ;;
            --server-image) rerun_option_check $# $1; SERVER_IMAGE=$2 ; shift ;;
            --server-ram) rerun_option_check $# $1; SERVER_RAM=$2 ; shift ;;
            --server-description) rerun_option_check $# $1; SERVER_DESCRIPTION=$2 ; shift ;;
            --public-ip) rerun_option_check $# $1; PUBLIC_IP=$2 ; shift ;;
            --private-ip) rerun_option_check $# $1; PRIVATE_IP=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$APIKEY" ] && APIKEY="$(rerun_property_get $RERUN_MODULE_DIR/options/apikey DEFAULT)"
    # Check required options are set
    [ -z "$APIKEY" ] && { echo >&2 "missing required option: --apikey" ; return 2 ; }
    [ -z "$SECRET" ] && { echo >&2 "missing required option: --secret" ; return 2 ; }
    [ -z "$SERVER_NAME" ] && { echo >&2 "missing required option: --server-name" ; return 2 ; }
    [ -z "$SERVER_IMAGE" ] && { echo >&2 "missing required option: --server-image" ; return 2 ; }
    [ -z "$SERVER_RAM" ] && { echo >&2 "missing required option: --server-ram" ; return 2 ; }
    [ -z "$SERVER_DESCRIPTION" ] && { echo >&2 "missing required option: --server-description" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
APIKEY=
SECRET=
SERVER_NAME=
SERVER_IMAGE=
SERVER_RAM=
SERVER_DESCRIPTION=
PUBLIC_IP=
PRIVATE_IP=


