# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Sat Jan  5 13:46:44 PST 2013
#
#/ usage: gogrid:api  --apikey <>  --secret <>  --method <> [ --server <https://api.gogrid.com/api>] [ --format <json>] [ --version <1.9>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --apikey) rerun_option_check $# ; APIKEY=$2 ; shift ;;
            --secret) rerun_option_check $# ; SECRET=$2 ; shift ;;
            --method) rerun_option_check $# ; METHOD=$2 ; shift ;;
            --server) rerun_option_check $# ; SERVER=$2 ; shift ;;
            --format) rerun_option_check $# ; FORMAT=$2 ; shift ;;
            --version) rerun_option_check $# ; VERSION=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$SERVER" ] && SERVER="https://api.gogrid.com/api"
    [ -z "$FORMAT" ] && FORMAT="json"
    [ -z "$VERSION" ] && VERSION="1.9"
    # Check required options are set
    [ -z "$APIKEY" ] && { echo >&2 "missing required option: --apikey" ; return 2 ; }
    [ -z "$SECRET" ] && { echo >&2 "missing required option: --secret" ; return 2 ; }
    [ -z "$METHOD" ] && { echo >&2 "missing required option: --method" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
APIKEY=
SECRET=
METHOD=
SERVER=
FORMAT=
VERSION=


